### ISSUE TITLE
`npm` installs a different thing for `dist/leaflet.buffer.min.js`

### ISSUE THREAD

**Issue by fernandocanizo** [skeate/Leaflet.buffer#19]
Hello Jonathan,

I noticed `npm` installs a different version of the minified library and the one installed with `npm` doesn't work.

With `npm` I get a ~7 KB library, while the one on the repo is bigger than 300 KB.

Another confusing thing is that on the repo, latest release is `0.1.5`, while `npm` brings a `0.1.6` version. Finally in commit `2f5f53f` you bumped version... To `0.2.1`! (?)

It seems the sources for the code are different. Could you provide an unified source of thruth? Also fixing the versioning would be a good thing.

Thanks for your hard work. :)

**Comment by skeate** [comment]
Unfortunately, I do not currently own the npm package. I think what happened is that I didn't originally publish it to npm, and sort of abandoned the project for a while. Someone else presumably wanted to use it via npm, so they cloned/published it themselves.

I've gone through [the procedure](https://docs.npmjs.com/misc/disputes) to get the package under my control, but it hasn't been resolved yet (it's been a few weeks with no reply, so it should be resolved by npm soon).

As soon as I get it back, I'll publish a new version (which should be `0.2.1`, or maybe `0.2.2`).

The file size increase you're seeing is because I've included the relevant parts of JSTS into the built file. So, while that individual file is larger, you also don't need to include JSTS, which is by itself ~437kB. If anyone has any interest I can build two versions, with and without JSTS, in case someone actually needs the full JSTS separately.

**Comment by fernandocanizo** [comment]
Oh, I see. Hope they give you control. Is there anyway we can help? Maybe a vote system somewhere under npm organization? Did the author of the npm package replied to you?

**Comment by skeate** [comment]
I emailed him and CCed npm as per the dispute guidelines. That was on Feb 9th; npm replied on the 10th, so either tomorrow or the day after makes it three weeks (which I interpret as "a few").

**Comment by skeate** [comment]
[It's been published as 0.2.1!](https://www.npmjs.com/package/leaflet-buffer)
